USE [master]
GO
CREATE DATABASE [MemberManagement]
 
GO
ALTER DATABASE [MemberManagement] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MemberManagement] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MemberManagement] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MemberManagement] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MemberManagement] SET ARITHABORT OFF 
GO
ALTER DATABASE [MemberManagement] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MemberManagement] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MemberManagement] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MemberManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MemberManagement] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MemberManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MemberManagement] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MemberManagement] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MemberManagement] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MemberManagement] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MemberManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MemberManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MemberManagement] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MemberManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MemberManagement] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MemberManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MemberManagement] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MemberManagement] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MemberManagement] SET  MULTI_USER 
GO
ALTER DATABASE [MemberManagement] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MemberManagement] SET DB_CHAINING OFF 
GO

GO
USE [MemberManagement]
GO
/****** Object:  Table [dbo].[Members]    Script Date: 3/7/2022 4:39:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Members](
	[MemberID] [int] NOT NULL,
	[MemberName] [nvarchar](50) NOT NULL,
	[Email] [text] NOT NULL,
	[Password] [text] NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[Country] [nvarchar](50) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[Members] ([MemberID], [MemberName], [Email], [Password], [City], [Country]) VALUES (1, N'user', N'user@fstore.com', N'user@', N'HN', N'VN')
GO
USE [master]
GO
ALTER DATABASE [MemberManagement] SET  READ_WRITE 
GO
